refactor: Ajuste pipeline do gateway para ALB

diff --git a/.github/workflows/infra-complete.yml b/.github/workflows/infra-complete.yml
--- a/.github/workflows/infra-complete.yml
+++ b/.github/workflows/infra-complete.yml
@@ -41,42 +41,40 @@ jobs:
       run: |
         aws eks update-kubeconfig --region us-east-1 --name lncr-prd-eks
 
-    
-
-    - name: Get NLB Listener ARN from EKS
+    - name: Get ALB Listener ARN from EKS
       run: |
-        # Use diretamente o ARN conhecido do NLB
-        NLB_ARN=$(aws elbv2 describe-load-balancers --query "LoadBalancers[].LoadBalancerArn" --output text | grep lncr | head -1)
-        echo "NLB_ARN found: $NLB_ARN"
+        # Use diretamente o ARN conhecido do ALB
+        ALB_ARN=$(aws elbv2 describe-load-balancers --query "LoadBalancers[?LoadBalancerName=='$ALB_NAME'].LoadBalancerArn" --output text)
+        echo "ALB_ARN found: $ALB_ARN"
 
-        NLB_LISTENER_ARN=$(aws elbv2 describe-listeners --load-balancer-arn $NLB_ARN --query "Listeners[0].ListenerArn" --output text)
-        echo "NLB_LISTENER_ARN found: $NLB_LISTENER_ARN"
+        ALB_LISTENER_ARN=$(aws elbv2 describe-listeners --load-balancer-arn $ALB_ARN --query "Listeners[0].ListenerArn" --output text)
+        echo "ALB_LISTENER_ARN found: $ALB_LISTENER_ARN"
         
-        if [ -z "$NLB_LISTENER_ARN" ]; then
-          echo "Error: NLB Listener ARN not found"
+        if [ -z "$ALB_LISTENER_ARN" ]; then
+          echo "Error: ALB Listener ARN not found"
           exit 1
         fi
-        echo "NLB_LISTENER_ARN=$NLB_LISTENER_ARN" >> $GITHUB_ENV
+        echo "ALB_LISTENER_ARN=$ALB_LISTENER_ARN" >> $GITHUB_ENV
 
     - name: Get Function ARN
       run: |
         
-        FUNCTION_ARN=$(aws lambda get-function --function-name lncr-prd-custom-authorizer --query 'Configuration.FunctionArn' --output text)
+        FUNCTION_ARN=$(aws lambda get-function --function-name $FUNCTION_NAME --query 'Configuration.FunctionArn' --output text)
         echo "FUNCTION_ARN found: $FUNCTION_ARN"
         if [ -z "$FUNCTION_ARN" ]; then
           echo "Error: Function ARN not found"
-          exit 1
+          exit 1ep
         fi
         echo "FUNCTION_ARN=$FUNCTION_ARN" >> $GITHUB_ENV
 
-    - name: Deploy API Gateway Configuration with NLB
+    - name: Deploy API Gateway Configuration with ALB
       env:
-        TF_VAR_eks_dns_nlb: ${{ env.NLB_LISTENER_ARN }}
+        TF_VAR_eks_dns_nlb: ${{ env.ALB_LISTENER_ARN }}
       run: |
         terraform init
         terraform apply \
           -target=module.api_gateway \
-          -var="eks_nlb_listener_arn=${{ env.NLB_LISTENER_ARN }}" \
+          -var="eks_nlb_listener_arn=${{ env.ALB_LISTENER_ARN }}" \
           -var="lambda_function_arn=${{ env.FUNCTION_ARN }}" \
           -var-file="prd.tfvars" \
           -auto-approve
